eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: STOCK-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:8111/springboot7am
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
